### PR TITLE
Added line to Robot Controller display to show last build date

### PR DESCRIPTION
**Pull request by grassclipper**
My FTC team, Rhyme Know Reason, ran into the issue of not being able to tell if we were running the latest version of our code.  This commit adds a line to show the last build date.

### CODE REVIEW

**Comment by rgatkinson** [comment]
This is an interesting idea; thanks for the suggestion, though I think it might better belong in the about box of the app. I'll put it on the to do list.

**Comment by rgatkinson** [comment]
Grassclipper: Thanks for the suggestion. Rather than putting this in just the Swerve Library, this is instead going to appear in the next core SDK release so that *everyone* gets the benefit. 'Appreciate the inspiration, much.

**Comment by grassclipper** [comment]
Thank you! We are thrilled that you are including our code. In the previous
message you mentioned that it might be better off on the About page. Are
you planning on including it there or on the main screen?

**Comment by rgatkinson** [comment]
It will show up in the About screen.

**Pull request closed without merging**
